# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Connect-iPhone' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'ASHorizontalScrollView', '~> 1.2'
  pod 'PBWebViewController', '~>0.3'

  # Pods for Connect-iPhone

  target 'Connect-iPhoneTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
